name: JewelsCrystals
version: ${project.version}
main: org.minejewels.jewelscrystals.JewelsCrystals
api-version: 1.19
depend: [ AbyssLib, PlaceholderAPI ]
authors: [ Consciences ]
description: Custom currency for MineJewels!
