name: JewelsMinerals
version: ${project.version}
main: org.minejewels.jewelsminerals.JewelsMinerals
api-version: 1.19
depend: [ AbyssLib, PlaceholderAPI ]
authors: [ Consciences ]
description: Custom currency for MineJewels!
